//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceChange
    {
        public int product_code { get; set; }
        public int old_price { get; set; }
        public int new_price { get; set; }
        public int ID_user { get; set; }
        public System.DateTime date_change { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
    }
}
